version: "3"
services:
  devcontainer:
    container_name: frigate-devcontainer-trt
    # add groups from host for render, plugdev, video
    privileged: true # this may not be necessary for all setups
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "256mb"
    build:
      context: .
      # Use target devcontainer-trt for TensorRT dev
      target: devcontainer-trt
    deploy:    # <------------- Add this section
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # number of GPUs
              capabilities: [gpu]
    devices:
      - /dev/bus/usb:/dev/bus/usb
      # - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - .:/workspace/frigate:cached
      - ./web/dist:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/config/config.yml:ro
      - ./debug/media:/media/frigate
      - ./debug/db:/db:rw
      - .debug/model_cache:/config/model_cache
      # Create the trt-models folder using the documented method of generating TRT models
      - ./debug/trt-models:/trt-models
      - /dev/bus/usb:/dev/bus/usb
    # volumes:
    #   - /etc/localtime:/etc/localtime:ro
    #   - /home/ubuntu/Gotcha/docker/config.yml:/config/config.yml
    #   - /mnt/md0/gotcha-footage/:/media/frigate
    #   - /home/ubuntu/Gotcha/docker/db/:/db
    #   - /home/ubuntu/Gotcha/trt-models:/trt-models
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    network_mode: host
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      PLUS_API_KEY: "01344070-b04e-47b6-84af-f9948d8ebd38:5bc0338b173153cfe36adeb3999cbd3a72d2add8"
      PLUS_API_HOST: "https://api.frigate.video"
      RETRAIN_HOST: "http://10.0.10.49:5003"
      REACT_APP_RETRAIN_HOST: "10.0.10.49:5003"

# networks:
#   my_bridge_network:
#     driver: bridges