version: "3"
services:
  devcontainer:
    container_name: frigate-devcontainer-trt
    # add groups from host for render, plugdev, video
    group_add:
      - "109" # render
      - "110" # render
      - "44"  # video
      - "46"  # plugdev
    shm_size: "256mb"
    build:
      context: .
      # Use target devcontainer-trt for TensorRT dev
      target: devcontainer-trt
    deploy:
          resources:
              reservations:
                  devices:
                      - driver: nvidia
                        count: 1
                        capabilities: [gpu]
    devices:
      - /dev/bus/usb:/dev/bus/usb
      # - /dev/dri:/dev/dri # for intel hwaccel, needs to be updated for your hardware
    volumes:
      - .:/workspace/frigate:cached
      - ./web/dist:/opt/frigate/web:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/frigate
      # Create the trt-models folder using the documented method of generating TRT models
      - ./debug/trt-models:/trt-models
      - .debug/db:/db
      - /dev/bus/usb:/dev/bus/usb
    network_mode: host
    environment:
      FRIGATE_RTSP_PASSWORD: "password"
      PLUS_API_KEY: "d61cb8b3-a0ac-4224-a1be-eac75ad29446:f43208789024aebe25203fe68e8b61784f4b0424"